### ISSUE TITLE
[功能建议] 允许更改首页副标题打字机速度

### ISSUE THREAD

**Issue by antonio0831** [EvanNotFound/hexo-theme-redefine#106]
**功能概述**
允许在Redefine Config中更改首页打字机速度
如下：
```yaml
first_screen:
    enable: true
    .......
    title: Theme Redefine # the title in the middle of the first screen. HTML supported (e.g. svg html code of your logo)
    subtitle: 
      enable: false
      list: ['Redefine Your Writing‘, 'Random Stuff']
      speed: 100 # The speed of the typewriter, in letter per ms
    ...
```
