### ISSUE TITLE
[功能建议] 建议增加可选分类页全部展示/分页展示

### ISSUE THREAD

**Issue by ncwzdlsd** [EvanNotFound/hexo-theme-redefine#128]
**功能概述**
鉴于 https://github.com/EvanNotFound/hexo-theme-redefine/issues/79 所述问题，建议增加一个把每一个分类页面内的文章全部展示（即归档页面展示方式）的 `bool` 值

**Comment by EvanNotFound** [comment]
好的

**Comment by EvanNotFound** [comment]
请查看：https://github.com/hexojs/hexo-generator-category

只要在 Hexo 站点配置文件写上

```yaml
category_generator:
  per_page: 0
  order_by: -date
```

就可以
