### ISSUE TITLE
[功能建议] 增加自定义CDN

### ISSUE THREAD

**Issue by momo54181** [EvanNotFound/hexo-theme-redefine#145]
**功能概述**
增加自定义CDN

```
CDN:
  # The CDN provider of internal scripts (主题内部 js 的 cdn 配置)
  # option: local/elemecdn/jsdelivr/unpkg/cdnjs/custom
  # Dev version can only choose. ( dev版的主题只能设置为 local )
  internal_provider: jsdelivr

  # The CDN provider of third party scripts (第三方 js 的 cdn 配置)
  # option: elemecdn/jsdelivr/unpkg/cdnjs/custom
  third_party_provider: jsdelivr

  # Add version number to CDN, true or false
  version: true

  # Custom format
  # For example: https://cdn.staticfile.org/${cdnjs_name}/${version}/${min_cdnjs_file}
  custom_format: https://cdn1.tianli0.top/npm/${name}@latest/${file}
```
