### ISSUE TITLE
[BUG] 关闭 pjax 后点击侧栏中的项目会在新标签页打开页面

### ISSUE THREAD

**Issue by bianyukun1213** [EvanNotFound/hexo-theme-redefine#153]
**提交前检查单**
- [x] 已经尝试执行 `hexo clean`，问题仍然存在
- [x] 已经更新到主题最新版本，详见 [官方文档 #更新](https://redefine-docs.ohevan.com/docs/quick-start/update)
- [x] 如果刚更新完主题出现此问题，已经确认同步了主题配置文件，[官方文档 #同步配置文件](https://redefine-docs.ohevan.com/docs/quick-start/update#%E8%BF%81%E7%A7%BB%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6)

**Bug 描述**

为了保证注入的自定义脚本正常运行，我关闭了 pjax。关闭 pjax 后再点击侧栏中的项目，页面会在新标签页打开，而不是原来 pjax 开启时“像从当前页面跳转”的效果。

``` yaml
sidebar:
    enable: true # Whether to enable sidebar
    position: left # Sidebar position. left, right
    first_item: info # First item in sidebar. menu, info
    announcement: # Announcement text
    links:
      # 归档: 
      #   path: /archives
      #   icon: fa-regular fa-box-archive # can be empty
      # 分类: 
      #   path: /tags
      #   icon: fa-regular fa-folder # can be empty
      # 标签: 
      #   path: /categories
      #   icon: fa-regular fa-tag # can be empty
      友链: 
        path: /links
        icon: fa-regular fa-link # can be empty
      开往: 
        path: https://www.travellings.cn/go.html
        icon: fa-regular fa-train # can be empty
      树洞: 
        path: /hollow
        icon: fa-regular fa-note-sticky # can be empty
      关于: 
        path: /about
        icon: fa-regular fa-user-vneck-hair # can be empty
      # ...... # you can add more
```

**复现方法**

关闭 pjax。

**预期结果**

关闭 pjax 后，点击侧栏中的项目，页面跳转。

**电脑**

 - 操作系统：Windows 10
 - 浏览器：Mozilla Firefox
 - 版本：113.0.1

**其他**

我注意到，侧栏项目 a 标签的 `target` 设为 `_blank`，如果在新标签页打开页面是刻意的设计而不是 bug，请关闭本 issue。
