### ISSUE TITLE
[功能建议] 文章合集功能

### ISSUE THREAD

**Issue by pigeon-dove** [EvanNotFound/hexo-theme-redefine#161]
**功能概述**
希望能够添加专栏功能（即文章合集功能）。虽然当前版本可以使用tag+侧边导航栏实现类似效果，但还是希望能有一个专门的功能。很多博文是一个系列的，放在一起会易于查询和阅读。

**图片描述**
如图所示，图片来自网络
![image](https://github.com/EvanNotFound/hexo-theme-redefine/assets/47208796/768cfe23-8e56-45f2-b3ec-9cfa6c73eb1e)

**Comment by EvanNotFound** [comment]
试了一下，目前技术能力有限，hexo官方文档写的真的是依托答辩，实在写不出来了。实在抱歉。

我的主要思路是在 config 里面的 sidebar 增加这一段：

```yaml
      Test:
        tag: demo123
        icon: fa-regular fa-tags
```
然后自动生成链接到这个 tag。 但是官方没有提供这个 helper，我也不会写，所以就暂时搁置了。
