### ISSUE TITLE
v2.1.5 更新到 v2.2.0 指南

### ISSUE THREAD

**Issue by EvanNotFound** [EvanNotFound/hexo-theme-redefine#167]
## 配置文件更改

本部分是主题配置文件 `_config.redefine.yml` 作出的更改
### Comment 评论部分
增加了 `Giscus` 评论系统，请对照本部分进行添加（点击可查看上下文）

https://github.com/EvanNotFound/hexo-theme-redefine/blob/8f907266195f5e54e79de762664f43a48f9afce4/_config.yml#L287-L324

### Articles 文章部分
增加了 `mobile_limit` 移动端推荐文章选项（点击可查看上下文）
https://github.com/EvanNotFound/hexo-theme-redefine/blob/8f907266195f5e54e79de762664f43a48f9afce4/_config.yml#L271-L284

## 友链格式更改

本部分是友情链接格式更改，请打开站点目录下的 `source/data/links.yml`

增加了链接分类功能，所以请从原先的格式：

```yaml
- name: Example Site
  link: https://example.com
  description: Example Site Description
  avatar: https://www.youtube.com/watch?v=dQw4w9WgXcQ
- name: Example Site 2
  link: https://example.com
  description: Example Site Description
  avatar: https://www.youtube.com/watch?v=dQw4w9WgXcQ
- ...
```
改成
```yaml
- links_category: Normal #分类名称
  has_thumbnail: false #是否显示网站大图
  list: 
    - name: Example Site
      link: https://example.com
      description: Example Site Description
      avatar: https://www.youtube.com/watch?v=dQw4w9WgXcQ
      thumbnail: #网站大图，需要开启 has_thumbnail。没开可以不填
    - name: Example Site 2
      link: https://example.com
      description: Example Site Description
      avatar: https://www.youtube.com/watch?v=dQw4w9WgXcQ
    - ...
```

可以配置多个友链分类，示例配置请查看文档：https://redefine-docs.ohevan.com/page_templates/friends

最终效果：

<img width="1624" alt="Screenshot 2023-06-22 at 2 29 11 PM" src="https://github.com/EvanNotFound/hexo-theme-redefine/assets/68590232/e249b21c-3279-4111-9809-f8500069f703">
