### ISSUE TITLE
Two Questions

### ISSUE THREAD

**Issue by 825i** [EvanNotFound/hexo-theme-redefine#182]
Sorry for asking here but I have tried everything to find a way to do these two things.

Firstly, thank you so much for this **incredible** theme! I absolutely love it and it will be perfect for what I am trying to do.

I have my blog here: [placeholder](https://blog.xtu.icu/)

____________________________________

### First question:

What I would like is at the top, where "**About**" link is, to link to a specific **page** on my blog. That is, a page which is separate from the way **posts** are displayed. Similar to in Wordpress when you make a page, it is treated independently to a post. Please excuse me if my question is confusing.

I have my installation directory as below:

![Screenshot 2023-07-13 155546](https://github.com/hexojs/hexo/assets/58630825/d83baf62-b811-4a6b-b768-2f89854c08c6)

According to the Docs: https://hexo.io/docs/writing
I should be able to put new pages in `root/source` but then my question is, how do I link them? i.e. how do I make the "About" link at the top, point to the `root/source/about.md`?

____________________________________

### Second question:

All of my posts have the wrong date. I have changed the format from YYYY-MM-DD to, DD-MM-YYYY, but the date is still starting from 1970?
`  01-01-1970 03:00 Created  13-07-2023 00:35:27`
See here: https://blog.xtu.icu/1970/01/01/template/

How do I change it to reflect the current date and time? I have looked all through the theme and cannot find out how to do this.

____________________________________

Thank you so much for any help!

**Comment by EvanNotFound** [comment]
Hi!

Thank you so much for using my theme. I am happy to help here.

### First Question

If you make a page in hexo, in this case, the `about` page, the markdown file should be in the directory of `source/about/index.md`. In Hexo, the folder represents pages, and the content is in the `index.md` under the folder. After generation, you will be able to access the page by typing `https://yourwebsite.com/about`

If you want to add the page to the navigation bar, in your `_config.redefine.yml`, in the `NAVIGATION` part, you will add:

```yaml
# NAVIGATION BAR >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
navbar:
  ......
  links:
    ......
    About: #this is the name to display in the nav bar
      path: /about #path to the page, in this case, to the folder's name. 
      icon: fa-regular fa-link # the icon before the nav bar item
    ......
# NAVIGATION BAR <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end
```

### Second Question

Please write all your date in the post front matter as `YYYY-MM-DD HH:MM`. This should solve the problem.

If you have any further questions, feel free to ask me.
