### ISSUE TITLE
[BUG] Home Banner Title Loss!

### ISSUE THREAD

**Issue by 1chooo** [EvanNotFound/hexo-theme-redefine#194]
**Describe the bug**
I have follow the steps to change the `home_banner.title` into my name. However, it does not change, it still be the default "Theme Redefine"

**To Reproduce**
1. go to `_config.redefine.yml`
2. Find the `home_banner.title` and rename into `1chooo's Blog`
3. `hexo clean`, `hexo generate`, `hexo server`
4. See error!!! `home_banner.title` still be the "Theme Redefine"

**Expected behavior**
"Theme Redefine" will change into "1chooo's Blog"

**Screenshots**

The "home_banner.title" still be the "Theme Redefine"
<img width="1280" alt="Screen Shot 2023-07-30 at 12 58 29 AM" src="https://github.com/EvanNotFound/hexo-theme-redefine/assets/94162591/e6344979-fc32-44e5-a54e-34aa8245ed69">

**Desktop (please complete the following information):**
 - OS: MacOS v12.6
 - Browser [Brave]
 - Version [v.1.52.130]

**Additional context**
My `_config.redefine.yml`
```yml
home_banner:
  # Whether to enable home banner
  enable: true
  # style of home banner
  style: fixed # static or fixed
  # Home banner image
  image: 
    light: /images/NCU.png # light mode
    dark: /images/NCU.png # dark mode
  # Home banner title
  title: 1chooo's Blog
  # Home banner subtitle
```

BR,
Hugo ChunHo Lin

**Comment by EvanNotFound** [comment]
The title in the menu bar is configured by `info.title`, not homebanner

**Comment by EvanNotFound** [comment]
![image](https://github.com/EvanNotFound/hexo-theme-redefine/assets/68590232/36b9c67d-4598-4fed-942b-a8759a938665)

**Comment by 1chooo** [comment]
@EvanNotFound Sorry that I use the old version of `base_info.title`, I have changed into `base.title`. I sincerely apologise for my mistake, thank you for your assistance

```yml
# My Old version code and not work
base_info:
  title: 1chooo's Blog # Site title
  author: Hugo ChunHo Lin # Author name
  url: https://1chooo.github.io/1chooo-blog # Site url
  # Logo image (You can use local image, image external link or don’t fill)
  # logo image on the left of the navigation bar
  logo_img: /images/favicon.ico

# This work!
info:
  title: 1chooo's Blog # Site title
  author: Hugo ChunHo Lin # Author name
  url: https://1chooo.github.io/1chooo-blog # Site url
  # Logo image (You can use local image, image external link or don’t fill)
  # logo image on the left of the navigation bar
  logo_img: /images/favicon.ico
```

BR, 
Hugo ChunHo Lin
