### ISSUE TITLE
[BUG] Home Banner Title Cannot back to Home Page

### ISSUE THREAD

**Issue by 1chooo** [EvanNotFound/hexo-theme-redefine#197]
**Describe the bug**
I have configured the `info.title` and `info.url`. However, when I click the title, it doesn't take me back to the home page; instead, I still need to click the home button to return to the home page.

Below is my `_config.redefine.yml` setting:
```yml
info:
  # Site title
  title: 1chooo's Blog
  # Author name
  author: Hugo ChunHo Lin
  # Site URL
  url: https://1chooo.github.io/1chooo-blog
```

**To Reproduce**
1. Go to the arbitrarily page in my web: https://1chooo.github.io/1chooo-blog/2023/07/31/unboxing/apple_fans/
2. Click on title in `navbar`
3. See error

**Expected behavior**
If I click the title in the navbar, it will return to home page.

**Screenshots**

https://github.com/EvanNotFound/hexo-theme-redefine/assets/94162591/b851e1e0-be6b-4bf8-ae4e-0721174943b4

**Desktop (please complete the following information):**
- OS: MacOS v12.6
- Browser [Brave]
- Version [v.1.52.130]

If there is any problem, please DM me directly.
BR,
@1chooo
