### ISSUE TITLE
[BUG] 友情链接异常

### ISSUE THREAD

**Issue by IcePigeons** [EvanNotFound/hexo-theme-redefine#239]
**提交前检查单**
- [x] 已经尝试执行 `hexo clean`，问题仍然存在
- [x] 已经更新到主题最新版本，详见 [官方文档 #更新](https://redefine-docs.ohevan.com/getting-started#%E6%9B%B4%E6%96%B0)
- [x] 如果刚更新完主题出现此问题，已经确认同步了主题配置文件，[官方文档 #同步配置文件](https://redefine-docs.ohevan.com/getting-started#%E8%BF%81%E7%A7%BB%E9%85%8D%E7%BD%AE)

**Bug 描述**
·······_config.redefine.yml···············
```
navbar:
  links:
    Friends: #取名随意
      icon: fa-solid fa-link #图标
      path: /links/
```
·······目录···············
![image](https://github.com/EvanNotFound/hexo-theme-redefine/assets/59303886/273f6eb1-2f93-4a88-bcf7-e042f2d7caa8)
········links/index.md············
```
---
title: Links
date: 2023-09-01 14:16:07
---
```
·········_data/links.yml···········
```
- links_category: Elites
  has_thumbnail: true
  list:
    - name: EvanNotFound's Blog
      link: https://ohevan.com
      description: 用香港记者的速度更新文章
      avatar: https://evan.beee.top/avatar.png
      thumbnail: https://img1.imgtp.com/2023/06/19/Jegvz84P.png # has_thumbnail 为 true 时才需要

- links_category: Normal
  has_thumbnail: false
  list:
    - name: Example Site
      link: https://example.com
      description: Example Site Description
      avatar: https://www.youtube.com/watch?v=dQw4w9WgXcQ
    - name: Example Site 2
      link: https://example.com
      description: Example Site Description
      avatar: https://www.youtube.com/watch?v=dQw4w9WgXcQ

- ......
```

**复现方法**
跟随友情链接文档进行，但是导航菜单跳转报异常

**预期结果**
预期应该出现友链页面，但是并没有(操作全按友情链接的文档的操作 https://redefine-docs.ohevan.com/page_templates/friends)

**截图**
![image](https://github.com/EvanNotFound/hexo-theme-redefine/assets/59303886/d1385e53-0a7e-424b-8b2d-3f37b8f038c6)

**电脑（请填写以下信息）：**
 - 操作系统： Windows11
 - 浏览器:  Firefox
 - 版本 117.0

**移动端（请填写以下信息）：**
 - 设备：[例如 iPhone 14]
 - 操作系统：[例如 iOS16.1]
 - 浏览器 [例如 Chrome, Safari]
 - 版本 [例如 108]

**其他**
如有其他内容，请提供
