### ISSUE TITLE
[求助] 有关2.5.0版本Tags页面无法显示的问题

### ISSUE THREAD

**Issue by S1eepy-Amon** [EvanNotFound/hexo-theme-redefine#283]
# 问题描述

我在本地搭建博客的时候遇到了Tags页面无法渲染的问题

![image](https://github.com/EvanNotFound/hexo-theme-redefine/assets/149855258/c3dc3eee-134c-427a-b9a4-a22b76be2279)

确认已经创建了对应url的链接，尝试使用过`hexo clean`清除缓存重新生成，同时`hexo g`可以在`public/tags/`下生成`index.html`

`source/tags/index.md`内容如下
```markdown
---
title: tags
date: 2023-11-05 11:14:36
type: tags
---
```

在`_config.redifine.yml`中有关tags的选项如下

```yaml
navbar:
  links:
    Tags:
        icon: fa-solid fa-tags
        path: /tags/

home:
  sidebar:
    links:
      Tags: 
        path: /tags 
        icon: fa-regular fa-tags # can be empty
  tags:
    enable: true  # Whether to enable
    limit: 3  # Max number of tags to display

page_templates:
  tags_style: blur # blur, cloud
```

`_config.yml`中有关tags的选项如下

```yaml
# Directory
tag_dir: tags

# Category & Tag
tag_map:
```
