### ISSUE TITLE
[BUG] 行间公式未居中

### ISSUE THREAD

**Issue by Andonade** [EvanNotFound/hexo-theme-redefine#293]
### 提交 Issue 前检查清单

- [X] 已经尝试执行 `hexo clean`，问题仍然存在
- [X] [已经更新到主题最新版本](https://redefine-docs.ohevan.com/getting-started#%E6%9B%B4%E6%96%B0)
- [X] [如果刚更新完主题出现此问题，已经确认同步了主题配置文件](https://redefine-docs.ohevan.com/getting-started#%E8%BF%81%E7%A7%BB%E9%85%8D%E7%BD%AE)

### Bug 描述

我的 _config.yml 中有关 mathjax 的设置：
```yml
mathjax:
  tags: none               # or 'ams' or 'all'
  single_dollars: true     # enable single dollar signs as in-line math delimiters
  cjk_width: 0.9           # relative CJK char width
  normal_width: 0.6        # relative normal (monospace) width
  append_css: true         # add CSS to every page
  every_page: false        # if true, every page will be rendered by mathjax regardless the `mathjax` setting in Front-matter of each article
```
我的 Markdown 部分代码：
```markdown
- *\*闭包*

        定义
        $$
        \Sigma^{*}=\Sigma^{0}\cup\Sigma^{1}\cup\Sigma^{2}\cup\cdots
        $$

    - *+闭包*

        定义
        $$
        \Sigma^{+}=\Sigma^{1}\cup\Sigma^{2}\cup\Sigma^{3}\cup\cdots
        $$
```
但在网页上这样的行间公式并未居中

### 预期结果

行间公式本应该是居中的

### 截图

<img width="1440" alt="截屏2023-11-07 23 38 15" src="https://github.com/EvanNotFound/hexo-theme-redefine/assets/113428896/ce426623-0db1-4c11-ad81-bb3c95eaeb60">

### 电脑操作系统

macOS Sonoma 14.1

### 浏览器

Chrome

### 版本

v2.5.0
