### ISSUE TITLE
[BUG] 行内公式位置偏下

### ISSUE THREAD

**Issue by Andonade** [EvanNotFound/hexo-theme-redefine#300]
### 提交 Issue 前检查清单

- [X] 已经尝试执行 `hexo clean`，问题仍然存在
- [X] [已经更新到主题最新版本](https://redefine-docs.ohevan.com/getting-started#%E6%9B%B4%E6%96%B0)
- [X] [如果刚更新完主题出现此问题，已经确认同步了主题配置文件](https://redefine-docs.ohevan.com/getting-started#%E8%BF%81%E7%A7%BB%E9%85%8D%E7%BD%AE)

### Bug 描述

我的 mathjax 设置：
```yml
mathjax:
  tags: none               # or 'ams' or 'all'
  single_dollars: true     # enable single dollar signs as in-line math delimiters
  cjk_width: 0.9           # relative CJK char width
  normal_width: 0.6        # relative normal (monospace) width
  append_css: true         # add CSS to every page
  every_page: false        # if true, every page will be rendered by mathjax regardless the `mathjax` setting in Front-matter of each article
```
部分 Markdown 代码：
```markdown
- *幂运算*

        设 $\Sigma$ 为字母表，$n$ 为任意自然数，定义

        1. $\Sigma^{0}=\lbrace\epsilon\rbrace$
        2. 设 $x\in\Sigma^{n-1}, a\in\Sigma$ ，则 $ax\in\Sigma^{n}$
        3. $\Sigma^{n}$ 中的元素只能有以上两种方式生成
```
显示效果在截图中可以看到，显然是偏下了

### 截图

在我的电脑上：
<img width="332" alt="截屏2023-11-15 16 35 41" src="https://github.com/EvanNotFound/hexo-theme-redefine/assets/113428896/a6a8fd52-69b6-4d46-99b8-52977d2e017a">

在我朋友的电脑上：
![image](https://github.com/EvanNotFound/hexo-theme-redefine/assets/113428896/b0a67dc3-3a81-468d-86fd-c0510a7bab2d)

### 电脑操作系统

macOS Sonoma 14.1.1 & Windows 11

### 浏览器

Chrome & Edge

### 版本

v2.5.2
