### ISSUE TITLE
[功能建议]：更改社交链接和下拉箭头的位置

### ISSUE THREAD

**Issue by Huasushis** [EvanNotFound/hexo-theme-redefine#316]
### 功能描述

P.S. 社交链接地位置改了有一些些不习惯（）

希望能增加社交链接放在左边、下拉箭头放在右边和社交链接像原来一样放在标题下方的选项。

**Comment by EvanNotFound** [comment]
将在下个版本新增，目前如需居中，可以用主题的 `inject` 加入以下代码

```yaml
# INJECT >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
inject:
  # Whether to enable inject
  enable: true
  # Inject custom head html code
  head:
    - "<style> .home-banner-container .content div:nth-child(2) { justify-content: center !important;  } .home-banner-container .content div:nth-child(2) div:first-child { display: none !important; } </style>"
```
