### ISSUE TITLE
[功能建议]：Allow disable the home banner background animation

### ISSUE THREAD

**Issue by sunnyy02** [EvanNotFound/hexo-theme-redefine#396]
### 功能描述

Can you provide the config that allows to disable the home banner background image animation?
So users can see the home page articles directly, without the need to scroll each time.
Thanks

**Comment by EvanNotFound** [comment]
You can just use custom injection code.

In `_config.redefine.yml`, navigate to `inject` section and change it as following

```yaml
# INJECT >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# Docs: https://redefine-docs.ohevan.com/inject
inject:
  enable: true
  head: 
    - "<style> .home-banner-container{ display:none; } .home-banner-background { filter: blur(0px) !important; } </style>"
    -
  # Inject custom footer html code
  footer:
    -
    -
# INJECT <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end
```
