### ISSUE TITLE
[BUG] H2 标题 加入单引号`xxx`代码 格式错乱

### ISSUE THREAD

**Issue by ChaoSBYNN** [EvanNotFound/hexo-theme-redefine#402]
### 提交 Issue 前检查清单

- [X] 已经尝试执行 `hexo clean`，问题仍然存在
- [X] [已经更新到主题最新版本](https://redefine-docs.ohevan.com/getting-started#%E6%9B%B4%E6%96%B0)
- [X] [如果刚更新完主题出现此问题，已经确认同步了主题配置文件](https://redefine-docs.ohevan.com/getting-started#%E8%BF%81%E7%A7%BB%E9%85%8D%E7%BD%AE)

## 版本

```ini
current v2.6.4  latest v2.6.4 
```

## source 文件

```markdown
## 17. 使用 `Supplier` 和 `Function` 接口
```

## 网站效果

![网站效果](https://github.com/user-attachments/assets/0ec4d46b-45f4-4eb4-afe6-cd7a405c2ef9)

## Markdown 工具预览

![工具预览](https://github.com/user-attachments/assets/31c0cca9-f1d9-48b7-8e34-3cf8ca78fd6a)

## _config.redefine.yml 配置

```yml
# SITE CUSTOMIZATION >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# Docs: https://redefine-docs.ohevan.com/basic/global
global:
  # Custom fonts
  fonts:
    # Chinese fonts
    chinese: 
      enable: true # Whether to enable custom chinese fonts
      family: Noto Sans SC # Font family
      url: https://fonts.googleapis.com/css2?family=Noto+Sans+SC:wght@400;500;700&display=swap # Font URL to CSS file
    # English fonts
    english: 
      enable: true # Whether to enable custom english fonts
      family: Noto Sans # Font family
      url: https://fonts.googleapis.com/css2?family=Noto+Sans:wght@400;500;700&display=swap # Font URL to CSS file

# ARTICLE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# Docs: https://redefine-docs.ohevan.com/posts/articles
articles:
  # Set the styles of the article
  style:
    font_size: 16px # Font size
    line_height: 1.5 # Line height
    image_border_radius: 14px # image border radius
    image_alignment: center # image alignment. left, center
    image_caption: true # Whether to display image caption
    link_icon: true # Whether to display link icon
    title_alignment: left # Title alignment. left, center
    headings_top_spacing: # Top spacing for headings from h1-h6
      h1: 2.7rem
      h2: 2.0rem
      h3: 1.6rem
      h4: 1.4rem
      h5: 1.2rem
      h6: 1.1rem
```

### 复现方法

```markdown
## 17. 使用 `Supplier` 和 `Function` 接口
```

```sh
hexo clean

hexo s
```

### 预期结果

![预期结果](https://github.com/user-attachments/assets/3aa47b4a-e764-4e95-a5fa-ca2a53d984a9)

### 截图

![异常效果](https://github.com/user-attachments/assets/3024cb54-29e0-4ca8-8719-16812572347f)
![期望效果](https://github.com/user-attachments/assets/eb0d0b34-83bc-4f34-b82b-0e78fcb6c7b5)

### 电脑操作系统

Windows

### 浏览器

Google Chrome, Microsoft Edge

### 版本

(Chrome)126.0.6478.127, (Edge)126.0.2592.102
