### ISSUE TITLE
[功能建议]：导航栏子菜单栏启用可选的图标

### ISSUE THREAD

**Issue by xzadudu179** [EvanNotFound/hexo-theme-redefine#433]
### 功能描述

在 `submenu` 中添加可选的 `icon` 参数且能够可选地显示图标

### 图片描述

![image](https://github.com/user-attachments/assets/28964185-71f5-4fa4-8160-41432503e5ed)
该页面为自己修改源代码的结果

### 其他

希望的 `navbar.links` 配置
```yml
    links:
        Home:
            path: /
            icon: fa-regular fa-planet-ringed # can be empty
        Timeline:
            path: /archives
            icon: fa-sharp fa-regular fa-timeline-arrow # can be empty
            submenus:
                Archives: # 将 submenu 内配置 path 和 icon
                    path: /archives
                    icon: fa-regular fa-box-archive
                Records:
                    path: /records
                    icon: fa-regular fa-pen
        # Status:
        #   path: https://status.ohevan.com/
        #   icon: fa-regular fa-chart-bar
        Masonry:
            icon: fa-regular fa-image
            path: /masonry
        Indexs:
            icon: fa-regular fa-bars
            submenus:
                Tags:
                    path: /tags
                    icon: fa-regular fa-tag
                Categories:
                    path: /categories
                    icon: fa-regular fa-inbox
        About:
            icon: fa-regular fa-sparkles
            path: /about
        #   submenus:
        #     Me:
        #       path: /about
        #       icon: fa-regular fa-sparkles
        Friends:
            icon: fa-regular fa-gift
            path: /links
        # ...... # you can add more
```
