### ISSUE TITLE
[BUG] 选择的代码块主题显示的颜色与hljs不同

### ISSUE THREAD

**Issue by RocketMaDev** [EvanNotFound/hexo-theme-redefine#437]
### 提交 Issue 前检查清单

- [X] 已经尝试执行 `hexo clean`，问题仍然存在
- [X] [已经更新到主题最新版本](https://redefine-docs.ohevan.com/getting-started#%E6%9B%B4%E6%96%B0)
- [X] [如果刚更新完主题出现此问题，已经确认同步了主题配置文件](https://redefine-docs.ohevan.com/getting-started#%E8%BF%81%E7%A7%BB%E9%85%8D%E7%BD%AE)

### Bug 描述

例如选择`atom-one-dark`，diff在深色主题下的颜色表现十分糟糕，但是highlight.js官方预览界面下颜色合适；看起来选择的配色方案与官方预览不同

### 复现方法

在`_config.redefine.yml`中设置相关配色

```yml
  code_block: # irrelevant settings skipped
    highlight_theme: # Color scheme for highlightjs code highlighting. For preview, see https://highlightjs.org/examples
      dark: atom-one-dark # dark mode theme, support: github-dark, monokai-sublime, vs2015, night-owl, atom-one-dark, nord, tokyo-night-dark, a11y-dark, agate
```

新建文件添加diff代码块

### 预期结果

![屏幕截图_20240911_193600](https://github.com/user-attachments/assets/f4a652b2-d84f-407a-99b7-31ccf65d56ff)

### 截图

![屏幕截图_20240911_193646](https://github.com/user-attachments/assets/da0716b5-a1d0-48b3-a7f6-ac93d94b3cd6)

### 电脑操作系统

Arch Linux

### 浏览器

Edge

### 版本

128
