### ISSUE TITLE
[BUG] 较长的行间公式出现遮挡

### ISSUE THREAD

**Issue by Gypsophila-cx** [EvanNotFound/hexo-theme-redefine#442]
### 提交 Issue 前检查清单

- [X] 已经尝试执行 `hexo clean`，问题仍然存在
- [X] [已经更新到主题最新版本](https://redefine-docs.ohevan.com/getting-started#%E6%9B%B4%E6%96%B0)
- [ ] [如果刚更新完主题出现此问题，已经确认同步了主题配置文件](https://redefine-docs.ohevan.com/getting-started#%E8%BF%81%E7%A7%BB%E9%85%8D%E7%BD%AE)

### Bug 描述

MathJax配置：

```
mathjax:
  tags: none               # or 'ams' or 'all'
  single_dollars: true     # enable single dollar signs as in-line math delimiters
  cjk_width: 0.9           # relative CJK char width
  normal_width: 0.6        # relative normal (monospace) width
  append_css: true         # add CSS to every page
  every_page: false        # if true, every page will be rendered by mathjax regardless the `mathjax` setting in Front-matter of each article
  packages:                # additional packages to include
    -require
    -amscd   
``` 

使用默认"hexo-renderer-marked": "^6.0.0"进行渲染

Bug：在公式长度超出屏幕宽度时（尤其是在手机屏幕上容易发生），公式开头的一部分将被遮挡掉，尽管存在下方滑动条，但是无法滑动到能看出完整公式的地方，具体表现请查看示例图片。

### 复现方法

写一个足够长的公式，例如
$$
    \int |K(x,y)f(y)| d \nu(y) \leqslant \left[ \int |K(x,y)|d \nu(y) \right]^{1 / q} \left[ \int |K(x,y)| |f(y)|^p \right]^{1 / p} \leqslant C^{1 / q} \left[ \int |K(x,y)| |f(y)|^p d \nu(y) \right]^{1 / p}\text{ i.e } \int \left[ \int |K(x,y)f(y)| d \nu(y) \right]^p d \mu(x) \leqslant C^{p / q} \iint |K(x,y)| |f(y)|^p d \nu(y) d \mu(x).
$$

### 预期结果

底部滑动条可以滑动到可以看到公式的最左端部分。

### 截图

<img width="1105" alt="normal" src="https://github.com/user-attachments/assets/8f4a6309-c654-402e-bc10-f5b02aea82ec">

上述图片是在电脑端渲染得到的结果，配置文件中的`content_max_width`为1200px，在右侧目录展开时是正常的表现，滑动条可以左滑到看到公式最左端。当右侧目录收起时会出现轻微遮挡。

<img width="390" alt="bad" src="https://github.com/user-attachments/assets/dfa95072-3b68-4d21-a102-78d18a515c9e">

上述图片是在较窄的屏幕上渲染的结果（这里是在电脑端直接把浏览器窗口缩小模拟出的结果，在手机上效果类似），可以看到尽管滑动条已经在最左侧了，但是公式的开头依然无法显示出来。

<img width="979" alt="bad2" src="https://github.com/user-attachments/assets/77e5410e-369c-41f2-ad2e-f3509c2b9e10">

上图是在电脑端将配置文件中的`content_max_width`调小到默认的1000px之后的效果，此时即使是在电脑端也会出现遮挡。

### 电脑操作系统

Windows

### 浏览器

Chrome

### 移动端设备

小米

### 移动端操作系统

安卓
