### ISSUE TITLE
[BUG] 本地部署模式的essays说说时间异常

### ISSUE THREAD

**Issue by Ataidawa** [EvanNotFound/hexo-theme-redefine#465]
### 提交 Issue 前检查清单

- [X] 已经尝试执行 `hexo clean`，问题仍然存在
- [X] [已经更新到主题最新版本](https://redefine-docs.ohevan.com/getting-started#%E6%9B%B4%E6%96%B0)
- [X] [如果刚更新完主题出现此问题，已经确认同步了主题配置文件](https://redefine-docs.ohevan.com/getting-started#%E8%BF%81%E7%A7%BB%E9%85%8D%E7%BD%AE)

### Bug 描述

以下为`_config.yml`文件中的时区设置，更新2.8.1后出现说说时间异常问题
```yaml
# Site
title: Hexo
subtitle: ''
description: ''
keywords:
author: John Doe
language: zh-CN
timezone: 'Asia/Shanghai'
```

### 复现方法

按照教程正常提交说说就会出现该异常

### 预期结果

见截图右侧

### 截图

![image](https://github.com/user-attachments/assets/24a66fe4-aa80-4465-896e-63718dc712e8)

### 电脑操作系统

Windows 10

### 浏览器

Microsoft Edge

### 版本

130.0.2849.46
