### ISSUE TITLE
[BUG] x86asm语言代码块边框消失

### ISSUE THREAD

**Issue by skyI23** [EvanNotFound/hexo-theme-redefine#467]
### 提交 Issue 前检查清单

- [X] 已经尝试执行 `hexo clean`，问题仍然存在
- [X] [已经更新到主题最新版本](https://redefine-docs.ohevan.com/getting-started#%E6%9B%B4%E6%96%B0)
- [X] [如果刚更新完主题出现此问题，已经确认同步了主题配置文件](https://redefine-docs.ohevan.com/getting-started#%E8%BF%81%E7%A7%BB%E9%85%8D%E7%BD%AE)

### Bug 描述

按照[highlightjs官方文档](https://highlightjs.readthedocs.io/en/latest/supported-languages.html)设置代码语言为x86asm后代码块边框不显示。

### 复现方法

hexo 的 `_config.yml` 中的高亮配置如下：
```yaml
syntax_highlighter: highlight.js
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''
```
在文章中插入代码块：
```x86asm
mov    rsp, cr3
and    rsp, 0xffffffffffffe7ff
mov    cr3, rsp
```
代码类型设置为 `x86asm` 。

### 预期结果

代码块边框消失。

### 截图

![image](https://github.com/user-attachments/assets/8458026f-274c-4267-be33-9b8fa47f87d2)
![image](https://github.com/user-attachments/assets/8a8e60ee-b182-4564-a6de-898d308abe22)

### 电脑操作系统

Windows

### 浏览器

Chrome
