### ISSUE TITLE
[BUG]无法显示ICON

### ISSUE THREAD

**Issue by YANthinkn** [EvanNotFound/hexo-theme-redefine#500]
### 提交前检查

- [x] 我已执行 `hexo clean` 并重新生成，问题仍然存在
- [x] 我已更新到[最新版本](https://redefine-docs.ohevan.com/getting-started#%E6%9B%B4%E6%96%B0)
- [x] 我已确认[同步了主题最新配置文件](https://redefine-docs.ohevan.com/getting-started#%E8%BF%81%E7%A7%BB%E9%85%8D%E7%BD%AE)

### Bug 描述

问题描述：
home_banner.social_links.links中使用google-scholar icon无法显示

相关配置：
```yaml
links:
      github: xxx # your GitHub URL
      google-scholar: xxx

```

icon link：https://fontawesome.com/icons/google-scholar?f=brands&s=solid

### 复现步骤

如上添加配置

### 截图

<img width="181" alt="Image" src="https://github.com/user-attachments/assets/a0c901fe-aeb6-48a7-80ee-1452965e40f4" />

### 相关日志输出

```shell

```

### 操作系统

None

### 优先级

低（慢慢来）
