### ISSUE TITLE
[BUG] HTTP 和 HTTPS 获取的网站 ICON 不同

### ISSUE THREAD

**Issue by AstridStark25963** [EvanNotFound/hexo-theme-redefine#502]
### 提交前检查

- [x] 我已执行 `hexo clean` 并重新生成，问题仍然存在
- [x] 我已更新到[最新版本](https://redefine-docs.ohevan.com/getting-started#%E6%9B%B4%E6%96%B0)
- [x] 我已确认[同步了主题最新配置文件](https://redefine-docs.ohevan.com/getting-started#%E8%BF%81%E7%A7%BB%E9%85%8D%E7%BD%AE)

### Bug 描述

**问题描述**：
我修改并上传了我自己设计的网站 ICON，但通过 Google 搜索到的网站 ICON 仍然是 Redefine Theme 的默认 ICON。
https://www.google.com/s2/favicons?sz=64&domain=http://1lya.com 显示的是 Redefine Theme 的默认 ICON。
https://www.google.com/s2/favicons?sz=64&domain=https://1lya.com 显示的是我自己上传的 ICON。
我的网站网址：[Astrid's Fantasy World](https://1lya.com)
> 访问 `http://1lya.com` 会自动跳转到 `https://1lya.com`。

**配置文件**：
``` yaml
# IMAGE CONFIGURATION >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# Docs: https://redefine-docs.ohevan.com/basic/defaults
defaults:
  # Favicon
  favicon: /images/favicon.svg
  # Site logo
  logo: 
  # Site avatar
  avatar: /images/my-avatar.svg
# IMAGE CONFIGURATION <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end
```

### 复现步骤

> 并不是很清楚这个 BUG 的复现步骤，以下说明我的使用过程：
1. 将 `_config.redefine.yml` 文件中的 Site logo 改为我自己的 ICON 文件。
2. 执行 `hexo clean`, `hexo g`, `hexo d` 并在网站查看效果。
3. 网站效果改变，搜索引擎结果未改变。
4. 在 Google Search Console 重新索引网站，仍为 Redefine Theme 默认图标。

### 预期行为

HTTP 和 HTTPS 网站的 ICON 均为我自己上传的 ICON 展示效果。

### 截图

**网站显示效果**：
![Website Icon](https://github.com/AstridStark25963/ImageHosting/blob/main/image/20250214204211781.png?raw=true)

**Google 搜索效果**：
![Google Search](https://github.com/AstridStark25963/ImageHosting/blob/main/image/20250214204323838.png?raw=true)

**使用 Google 服务获取 `http://1lya.com` 图标**：
![Redefine Default Icon](https://github.com/AstridStark25963/ImageHosting/blob/main/image/20250214203752155.png?raw=true)

**使用 Google 服务获取 `https://1lya.com` 图标**：
![My Icon](https://github.com/AstridStark25963/ImageHosting/blob/main/image/20250214204027936.png?raw=true)

### 相关日志输出

```shell

```

### 使用的浏览器

Chrome

### 操作系统

Windows

### 浏览器版本

Chrome 133.0.6943.60

### 优先级

低（慢慢来）
