### ISSUE TITLE
代码没有样式

### ISSUE THREAD

**Issue by limeng0403** [EvanNotFound/hexo-theme-redefine#8]
已经设置了javascript

![](https://imgbed.iiba.fun/blog/WX20221019-134526@2x.png)

**Comment by EvanNotFound** [comment]
请提供链接，我复现一下

**Comment by limeng0403** [comment]
> 
_config.yml
```
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ""
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ""
```

目录：
![](https://imgbed.iiba.fun/blog/WX20221020-094310@2x.png)

console：
![](https://imgbed.iiba.fun/blog/WX20221020-094845@2x.png)

仓库地址：[https://github.com/limeng0403/blog_source](https://github.com/limeng0403/blog_source)
网站地址：[https://www.iiba.fun/2022/06/24/ES2022%E6%AD%A3%E5%BC%8F%E5%8F%91%E5%B8%83-%E6%9C%89%E5%93%AA%E4%BA%9B%E6%96%B0%E7%89%B9%E6%80%A7/](https://www.iiba.fun/2022/06/24/ES2022%E6%AD%A3%E5%BC%8F%E5%8F%91%E5%B8%83-%E6%9C%89%E5%93%AA%E4%BA%9B%E6%96%B0%E7%89%B9%E6%80%A7/)
